Provider: Yaml

# Database Settings
database:
  # Set to sqlite to use the SQLite3 database, and to mysql to use the MySQL, dblib to use MySQL via DBLib plugin.
  type: "sqlite"
  # SQLite Database Settings
  sqlite:
    db-file: "user-info.db"
  # MySQL / DBLib Database Settings
  mysql:
    host: "localhost"
    database: "justskyblock"
    port: 3306
    user: "root"
    password: "your-password-here"
