name: JustSkyblock
main: do1phin.mine2021.ServerAgent
version: "${pom.version}"
api: ["1.0.0"]
author: do1phin
description: Simple yet powerful skyblock server plug-in for PowerNukkit
website: http://skyblock.do1ph.in
load: STARTUP

permissions:
  justskyblock.general:
    description: "Allow access to general server feature"
    default: true
  justskyblock.skyblock:
    description: "Allow access to skyblock feature"
    default: true
  justskyblock.management:
    description: "Allow access to management feature"
    default: op