Provider: Yaml

prefix:
  info: "<§e안내§f>"
  notice: "<§e공지§f>"

text:
  general:
    guidebook: "§e가이드북"
  skyblock:
    protection-type:
      protection-type: "보호 수준"
      allow-only-owner: "나만"
      allow-invited: "초대된"
      allow-all: "모두"
    lock-type:
      protection-type: "접근 수준"
      allow-only-owner: "나만"
      allow-invited: "초대된"
      allow-all: "모두"
  blockgen:
    item-tag: "§e생성 블럭 §aLV."

message:
  general:
    on-player-join: "§e%player§f 님이 접속했습니다."
    on-player-quit: "§e%player§f 님이 나갔습니다."
    on-player-first-join: "§e%player§f 님이 서버에 처음 접속하셨습니다."
  skyblock:
    teleport-succeed: "§e%player§f 의 구역으로 이동했습니다."
    teleport-incoming: "§e%player§f 님이 내 구역에 도착 했습니다."
    teleport-succeed-self: "내 구역으로 이동했습니다."
    invite-succeed: "§e%player§f 님을 내 구역으로 초대했습니다."
    invite-received: "§e%owner§f 님의 구역으로 초대되었습니다."
    purge-succeed: "§e%player§f 님을 내 구역에서 추방했습니다."
    protection-type-updated: "내 구역의 보호 수준이 §e%protection-type§f 으로 설정 되었습니다."
    lock-type-updated: "내 구역의 접근 수준이 §e%lock-type§f 으로 설정 되었습니다."
  blockgen:
    blockgen-upgrade-succeed: "생성 블럭이 §e%level단계§f로 강화 되었습니다."
  management:
    on-player-kicked: "§e%reason§f 사유로 §e일시 추방§f 되셨습니다."
    on-player-banned: "§e%player§f 님은 §e%year년 %month월 %day일 %hour시 %minute분 §f까지 §e%reason§f 사유로 차단되었습니다."
    player-banned: "§e%player§f 님은 §e%year년 %month월 %day일 %hour시 %minute분 §f까지 §e%reason§f 사유로 차단된 상태입니다."

popup:
  general:
    on-player-join: "+%player"
    on-player-quit: "-%player"
  skyblock:
    protection-type-warning: "§e%player§7 님의 구역은 §e%protection-type§7 수준으로 보호되고 있습니다."

command:
  management:
    ban-command:
      command: "b"
      description: "유저를 차단합니다."
      usage: "/b <닉네임> <사유> <기간(일)>"
      parameter:
        player: "유저"
        reason: "사유"
        duration: "기간"
      format-error: "/b <닉네임> <사유> <기간(일)> 형식으로 입력해 주시기 바랍니다."
      ban-succeed: "§e%player§f 를 §e%reason§f 사유로 §e%duration일§f 동안 차단했습니다."
      ban-failed-playernotfound: "§4%player§f 를 찾을 수 없습니다."
    unban-command:
      command: "ub"
      description: "유저의 차단을 해제합니다."
      usage: "/ub <닉네임>"
      parameter:
        player: "유저"
      format-error: "/ub <닉네임> 형식으로 입력해 주시기 바랍니다."
      unban-succeed: "§e%player§f 님의 차단을 해제 했습니다."
      unban-failed: "§4%player§f 님은 차단되어있지 않습니다."
    kick-command:
      command: "k"
      description: "유저를 추방합니다."
      usage: "/k <닉네임> <사유>"
      parameter:
        player: "유저"
        reason: "사유"
      format-error: "/k <닉네임> <사유> 형식으로 입력해 주시기 바랍니다."
      kick-succeed: "§e%player§f 를 §e%reason§f 사유로 추방 했습니다."
      kick-failed-playernotfound: "§4%player§f 를 찾을 수 없습니다."
    group-command:
      command: "g"
      description: "유저의 칭호를 바꿉니다."
      usage: "/g <닉네임> <ID>"
      parameter:
        player: "유저"
        id: "그룹 ID"
      format-error: "/g <닉네임> <ID> 형식으로 입력해 주시기 바랍니다."
      update-succeed: "§e%player§f 를 분류 ID §e%id:%group-name§f 으로 분류했습니다."
      update-failed-idnotfound: "분류 ID §4%id§f 를 찾을 수 없습니다."
      update-failed-playernotfound: "§4%player§f 를 찾을 수 없습니다."
  skyblock:
    teleport-command:
      command: "이동"
      description: "내 구역 또는 다른 유저의 구역으로 이동합니다."
      usage: "/이동 또는 /이동 <닉네임>"
      parameter:
        player: "닉네임"
      teleport-failed-playernotfound: "§4%player§f 님을 찾을 수 없습니다."
      teleport-failed-locked: "§e%player§f 님의 구역은 §e%lock-type§f 수준으로 접근이 제한되어 있습니다."
    invite-command:
      command: "초대"
      description: "다른 유저를 내 구역으로 초대합니다."
      usage: "/초대 <닉네임>"
      parameter:
        player: "닉네임"
      format-error: "/초대 <닉네임> 형식으로 입력해 주시기 바랍니다."
      invite-failed-playeralradyinvited: "§e%player§f 님은 이미 내 구역에 초대되어 있습니다."
      invite-failed-playernotfound: "§4%player§f 님을 찾을 수 없습니다."
    purge-command:
      command: "추방"
      description: "내 구역으로 초대된 유저를 추방합니다."
      usage: "/추방 <닉네임>"
      parameter:
        player: "닉네임"
      format-error: "/추방 <닉네임> 형식으로 입력해 주시기 바랍니다."
      purge-failed-playernotfound: "§4%player§f 님을 찾을 수 없습니다."
      purge-failed-playernotinvited: "§4%player§f 님은 초대 목록에 존재하지 않습니다."
    invite-list-command:
      command: "목록"
      description: "내 구역에 초대된 유저 목록을 확인합니다."
      usage: "/목록"
      show-invited-list: "§e%invited-list§f 이 내 구역에 초대되어 있습니다."
      show-invited-list-empty: "아무도 내 구역에 초대되어 있지 않습니다."
    protection-type-command:
      command: "보호"
      description: "내 구역의 보호 수준을 설정합니다."
      usage: "/보호 <나만|초대된|모두>"
      parameter:
        protection-type: "보호 수준"
      format-error: "/보호 <나만|초대된|모두> 형식으로 입력해 주시기 바랍니다."
    lock-type-command:
      command: "접근"
      description: "내 구역의 접근 수준을 설정합니다."
      usage: "/접근 <나만|초대된|모두>"
      parameter:
        lock-type: "접근 수준"
      format-error: "/접근 <나만|초대된|모두> 형식으로 입력해 주시기 바랍니다."

form:
  welcome-form:
    title: "§l환영합니다!"
    content: "§eJustSkyblock§f 서버에 처음 접속하셨습니다.
    \n
    \n • §e가이드북§f을 확인 해주세요.
    \n
    \n • §e추가된 조합법들§f을 확인 해주세요.
    \n
    \n • 불편하신 사항이 있다면 §b[Staff]§f 칭호를 달고 있는 §b운영자§f에게 문의 해주세요.
    \n
    \n§eJustSkyblock§f 서버에서 즐거운 시간 보내시기를 바라겠습니다.
    \n
    \n§7JustSkyblock @2021
    "

guidebook:
  version: 1
  author: "§e§lJustSkyblock"
  content:
    - "page1 example
    \npage1 line2
    \nfor %player."
    - "page2 example
    \npage2 line2
    \nfor %player."